routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(
    [
        'prefix'=>'admin',
        'middleware'=>'roles',
        'roles'=>'admin'
    ]
    ,function(){
        Route::resource('users','AdminUserController');
        Route::resource('categories','AdminCategoryController');
        }
);
Route::group(
    [
        'prefix'=>'user',
        'middleware'=>'auth',
    ]
    ,function(){
    Route::get('upload','UserUploadController@index')->name('upload.index');
    Route::post('upload','UserUploadController@upload')->name('upload.save');
    Route::get('categories/{id}','PagesController@viewcategories')->name('viewcategory');

}
);

resources/views/admin/addcategory.blade.php
<?php $i=1;?>
@extends('adminlte::page')

@section('title', 'Add category')

@section('content')

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Add category</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
            </div>

            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <form action="{{route('categories.store')}}" method="post" autocomplete="off">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="category">Category</label>
                    <input type="text" name="category" class="form-control" id="category" aria-describedby="emailHelp" placeholder="Enter category">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <!-- /.box-body -->

    </div>
    <!-- /.box -->


@endsection

resources/views/admin/categories.blade.php
<?php $i=1;?>
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Categories</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
                <button type="button" class="btn btn-success"><a href="{{route('categories.create')}}">Add Category</a></button>
            </div>

            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-dark">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Category Name</th>
                </tr>
                </thead>
                <tbody>

                @if(count($categories)>0)
                    @foreach($categories as $category)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$category->name}}</td>
                        </tr>
                    @endforeach
                @endif

                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <!-- box-footer -->
    </div>
    <!-- /.box -->


@endsection

resources/views/admin/users.blade.php
<?php $i=1;?>
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Users</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
            </div>

            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-dark">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</td>
                </tr>
                </thead>
                <tbody>

                @if(count($users)>0)
                    @foreach($users as $user)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->


@endsection

resources/views/admin/userupload.blade.php
<?php $i=1;?>
@extends('layouts.app')

@section('title', 'upload')

@section('content')


    <div class="panel panel-default">
        @if(session('msg'))
            {{session('msg')}}
            @endif
        <div class="panel-heading">Upload File</div>

        <div class="panel-body">
            <form action="{{route('upload.save')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    <input type="text" name="title" value="{{old('title')}}" id="title" placeholder="Enter Title" class="form-control"/>
                </div>
                <div class="form-group">
                    <input type="text" name="author" value="{{old('author')}}" id="author" placeholder="Enter Author" class="form-control"/>
                </div>
                <div class="form-group">
                    <textarea  name="info" class="form-control" id="info" placeholder="Some info on Book"></textarea>
                </div>
                <div class="form-group">
                    <select class="form-control" name="category">
                        @if (count($allcategories) > 0)
                            @foreach($allcategories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
                <div class="form-group">
                    <input type="file" name="image" id="image" class="form-control" placeholder="img"/>
                </div>
                <div class="form-group">
                    <input type="file" name="book" id="book" class="form-control" placeholder="book"/>
                </div>
                <div class="form-group">
                    <button type="submit" name="uplaod" class="btn btn-primary btn-block">Upload Book</button>
                </div>
            </form>
        </div>
    </div>

@endsection